<a href="https://colab.research.google.com/github/alexayanar/colab/blob/master/NumPy_Fun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#A Super Quick NumPy Functionality Demonstration

To keep the data science imagination going, I kept working on small python projects. This is an example--a challenge set by freecodecamp.org. 

The project should contain a function called calculate that will take a list of 9 numbers, transform it into a 3x3 NumPy array, then spit out a dictionary containing the mean, variance, standard deviation, max, min, and sum of the whole array, as well as its axis 0 and axis 1. 

My approach was to create one function that called upon other functions to obtain the mean, variance, etc individually. 


In [3]:
import numpy as np

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0, 1, 2, 3, 4, 5, 6, 7, 8]


The reshape function starts us off. By creating an if/else statement, we're setting ourselves up for success! We wouldn't be able to comply and form a 3x3 NumPy array otherwise. 

In [30]:
def rs(list):
  if len(list) == 9:
    b = np.array([list])
    b = np.reshape(b, (3, 3))
    return(b)
  else:
    ValueError("List must contain nine numbers.")

Next on the list is creating all of the functions that will calculate the mean, variance, standard deviation, max, min, and sum of the array. For the purpose of efficiency, I tried using as little variables and lines as possible by placing the calculation parts directly into the return list. The return lists will eventually be compiled into a dictionary. 

In [45]:
def m(b):
  means = [np.mean(b, axis = 0), np.mean(b, axis = 1), np.mean(b)]
  return means

In [32]:
def var(b):
  variances = [np.var(b, axis = 0), np.var(b, axis = 1), b]
  return variances

In [33]:
def stde(b):
  stds = [np.std(b, axis = 0), np.std(b, axis = 1), np.std(b)]
  return stds

In [34]:
def mx(b):
  maxs = [np.max(b, axis = 0), np.max(b, axis = 1), np.max(b)]
  return maxs

In [35]:
def mn(b):
  mins = [np.min(b, axis = 0), np.min(b, axis = 1), np.min]
  return mins

In [36]:
def sm(b): 
  sums = [np.sum(b, axis = 0), np.sum(b, axis = 1), np.sum]
  return sums

Finally, we can create the final function! This function will reshape the list passed as an attribute into a 3x3 NumPy array, then spit out a dictionary using the functions we created and called. 

In [24]:
def calculate(list):
  b = rs(list)
  calculations = {
    "mean": m(b),
    "variance": var(b),
    "standard deviation": stde(b),
    "max": mx(b),
    "min": mn(b),
    "sum": sm(b)
  }
  return calculations


{'mean': {'mean1': array([3., 4., 5.]), 'mean2': array([1., 4., 7.]), 'meanf': 4.0}, 'variance': {'var1': array([6., 6., 6.]), 'var2': array([0.66666667, 0.66666667, 0.66666667]), 'varf': 6.666666666666667}, 'standard deviation': {'std1': array([2.44948974, 2.44948974, 2.44948974]), 'std2': array([0.81649658, 0.81649658, 0.81649658]), 'stdf': 2.581988897471611}, 'max': {'max1': array([6, 7, 8]), 'max2': array([2, 5, 8]), 'max': 8}, 'min': {'min1': array([0, 1, 2]), 'min2': array([0, 3, 6]), 'min': 0}, 'sum': {'s1': array([ 9, 12, 15]), 's2': array([ 3, 12, 21]), 's': 36}}


Let's try it out!

In [46]:
print(calculate([0, 1, 2, 3, 4, 5, 6, 7, 8]))

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0], 'variance': [array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])], 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]), array([0.81649658, 0.81649658, 0.81649658]), 2.581988897471611], 'max': [array([6, 7, 8]), array([0, 3, 6]), 0], 'min': [array([0, 1, 2]), array([0, 3, 6]), <function amin at 0x7f69f79c9c80>], 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), <function sum at 0x7f69f79c92f0>]}
